[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [ "@chainlink=node_modules/@chainlink", "@openzeppelin=node_modules/@openzeppelin" ]

[ rpc_endpoints ]
sepolia = "${SEPOLIA_RPC_URL}"
fuji = "${FUJI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
